<?php
/**
 * Copyright (c) 2015 eBay Enterprise, Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the eBay Enterprise
 * Magento Extensions End User License Agreement
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://www.ebayenterprise.com/files/pdf/Magento_Connect_Extensions_EULA_050714.pdf
 *
 * @copyright   Copyright (c) 2015 eBay Enterprise, Inc. (http://www.ebayenterprise.com/)
 * @license     http://www.ebayenterprise.com/files/pdf/Magento_Connect_Extensions_EULA_050714.pdf  eBay Enterprise Magento Extensions End User License Agreement
 *
 */
?>
<?php
/**
 * @see EbayEnterprise_RiskInsight_Block_System_Config_Testapiconnection
 */
?>
<?php $htmlId = $this->getHtmlId(); ?>
<button class="scalable" type="button" id="<?php echo $htmlId ?>">
	<span id="validation_result"><?php echo $this->getButtonLabel() ?></span>
</button>
<script type="text/javascript">
//<![CDATA[
	document.observe("dom:loaded", function() {
		var elemId = '<?php echo $htmlId ?>';
		var ajaxUrl = '<?php echo $this->getAjaxUrl() ?>';
		var apiValidation = new RiskInsightApiValidation(elemId, ajaxUrl);
	});
//]]>
</script>
