<?php
/**
 * Copyright (c) 2013-2016 Radial Commerce Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright   Copyright (c) 2013-2016 Radial Commerce Inc. (http://www.radial.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Radial_FraudInsight_Block_System_Config_Testapiconnection
 */
?>
<?php $htmlId = $this->getHtmlId(); ?>
<button class="scalable" type="button" id="<?php echo $htmlId ?>">
	<span id="validation_result"><?php echo $this->getButtonLabel() ?></span>
</button>
<script type="text/javascript">
//<![CDATA[
	document.observe("dom:loaded", function() {
		var elemId = '<?php echo $htmlId ?>';
		var ajaxUrl = '<?php echo $this->getAjaxUrl() ?>';
		var apiValidation = new RiskInsightApiValidation(elemId, ajaxUrl);
	});
//]]>
</script>
